import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';
import { Geist } from 'next/font/google';
import { cn } from '@/lib/utils';
import QueryProvider from '@/provider/QueryProvider';

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: '앱센터(Todo)',
  description: 'Generated by create next app',
};

// 필요한 static 폰트만 로딩-> globals.css에서 @font-face로 선언하면 중복 선언되는 꼴이므로 하나만 설정
const suite = localFont({
  src: [
    {
      path: '../public/fonts/SUITE-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/SUITE-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/SUITE-SemiBold.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../public/fonts/SUITE-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  display: 'swap',
  variable: '--font-suite', // CSS 변수 이름
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  ``;
  return (
    <html
      lang="ko"
      className={cn(
        'h-full',
        'antialiased',
        suite.variable,
        'font-sans',
        geist.variable
      )}
    >
      <body className="flex min-h-full flex-col" suppressHydrationWarning>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
