import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "앱센터(Todo)",
  description: "Generated by create next app",
};

const suite = localFont({
  src: "../../public/fonts/SUITE-Variable.woff2", // 폰트 파일 경로
  display: "swap",
  variable: "--font-suite", // CSS 변수 이름
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` ${suite.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col suppressHydrationWarning">
        {children}
      </body>
    </html>
  );
}
